PDFCertificateWeb/Controllers/FilesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PDFCertificateWeb.Data;
using PDFCertificateWeb.Models;
using PDFCertificateWeb.Services;
using PDFCertificateWeb.ViewModels;
using System.Text.Json;
using IHostingEnvironment = Microsoft.AspNetCore.Hosting.IHostingEnvironment;

namespace PDFCertificateWeb.Controllers
{
    public class FilesController : Controller
    {
        private readonly AppDBContext appDBContext;
        private readonly IHostingEnvironment hostingEnvironment;
        private readonly UserManager<AppUser> userManager;
        private readonly ICertificateService certificateService;

        public FilesController(AppDBContext appDBContext, IHostingEnvironment hostingEnvironment, UserManager<AppUser> userManager, ICertificateService certificateService)
        {
            this.appDBContext = appDBContext;
            this.hostingEnvironment = hostingEnvironment;
            this.userManager = userManager;
            this.certificateService = certificateService;
        }

        [HttpGet]
        [Authorize]
        public ViewResult Upload()
        {
            return View();
        }

        [Authorize]
        [HttpGet]
        public async Task<ViewResult> Index()
        {
            var user = await userManager.GetUserAsync(User);
            var certificate = appDBContext.Certificates.ToList().FirstOrDefault(x => x.AppUserId == user.Id);
            ViewBag.HasCertificate = certificate != null;
            ViewBag.FilesList = (await appDBContext.PDFFiles.ToListAsync()).OrderByDescending(x => x.UploadDate).ToList(); ;
            return View();
        }

        private void addConfigToTempFolder(string fileId, string path, Certificate cert)
        {
            string fullpath = Path.Combine(path,$"{fileId}.json");

            dynamic config = new
            {
                certificateStore = certificateService.GetCertificateStore(),
                certificateName = cert.Id,
                certificatePassword = cert.Password,
                fileId = fileId
            };

            string json = JsonSerializer.Serialize(config);
            System.IO.File.WriteAllText(fullpath, json);
        }

        private void addFileToTempFolder(IFormFile file, string name, string folder)
        {
            if (!Directory.Exists(folder)) Directory.CreateDirectory(folder);
            string filePath = Path.Combine(folder, name);
            using (FileStream fs = new FileStream(filePath, FileMode.Create))
            {
                file.CopyTo(fs);
            }
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Upload(FileUploadViewModel model)
        {
            if (ModelState.IsValid)
            {
                var file = model.File;
                var user = await userManager.GetUserAsync(User);
                var certificate = appDBContext.Certificates.ToList().FirstOrDefault(x => x.AppUserId == user.Id);
                if (certificate != null)
                {
                    string rootpath = hostingEnvironment.WebRootPath;
                    string temppath = Path.Combine(rootpath, "tempfiles/" + user.Id);
                    string fileId = Guid.NewGuid().ToString();
                    string uniqueFileName = $"{fileId}.pdf";

                    addFileToTempFolder(model.File, uniqueFileName, temppath);
                    addConfigToTempFolder(fileId, temppath, certificate);

                    PDFFileInfo newFile = new PDFFileInfo
                    {
                        Id = fileId,
                        Name = model.Name,
                        UserId = user.Id,
                        CertificateId = certificate.Id,
                        Path = "files/" + user.Id + "/" + uniqueFileName,
                        UploadDate = DateTime.Now
                    };

                    appDBContext.PDFFiles.Add(newFile);
                    appDBContext.SaveChanges();
                    return RedirectToAction("index");
                }
                else
                {
                    ModelState.AddModelError("Certificate", "Certificate not found.");
                }

            }

            return View(model);
        }

    }
}

PDFCertificateWeb/Controllers/UserController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using PDFCertificateWeb.Models;
using PDFCertificateWeb.ViewModels;

namespace PDFCertificateWeb.Controllers
{
    public class UserController : Controller
    {
        private readonly UserManager<AppUser> userManager;
        private readonly SignInManager<AppUser> signInManager;

        public UserController(UserManager<AppUser> userManager, SignInManager<AppUser> signInManager)
        {
            this.userManager = userManager;
            this.signInManager = signInManager;
        }

        [HttpGet]
        public IActionResult SignUp()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> SignUp(SignUpViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = new AppUser
                {
                    UserName = model.Username
                };

                var result = await userManager.CreateAsync(user, model.Password);

                if (result.Succeeded)
                {
                    await signInManager.SignInAsync(user, isPersistent: false);
                    return RedirectToAction("index", "home");
                }

                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                }
            }

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Logout()
        {
            await signInManager.SignOutAsync();
            return RedirectToAction("index", "home");
        }


        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginViewModel model, string? returnUrl = "")
        {
            if (ModelState.IsValid)
            {
                var result = await signInManager.PasswordSignInAsync(model.Username, model.Password, model.RememberMe, false);

                if (result.Succeeded)
                {
                    if (Url.IsLocalUrl(returnUrl))
                        return Redirect(returnUrl);
                    return RedirectToAction("index", "home");
                }
                      
                ModelState.AddModelError(string.Empty, "Usuario/Senha inválidos.");
            }

            return View(model);
        }
    }
}

PDFCertificateWeb/Views/Shared/_Empty.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PDFCertificateWeb</title>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons+Outlined" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    @RenderSection("Head", required: false)
</head>
<body>
    @RenderBody()
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

PDFCertificateWeb/Views/Shared/_Layout.cshtml
@inject SignInManager<AppUser> signInManager;
<!DOCTYPE html>
<html lang="en" style="height: 100%">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PDFCertificateWeb</title>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons+Outlined" rel="stylesheet">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PDFCertificateWeb.styles.css" asp-append-version="true" />
    @RenderSection("Head", required: false)

</head>
<body style="display: flex; flex-direction:column; height: 100%">
    <header class="blue">
        <nav class="container z-depth-0 blue">
            <div class="nav-wrapper">
                <a class="left" style="font-size: 1.2em; display: flex;" asp-area="" asp-controller="Home" asp-action="Index">
                    <i class="material-icons-outlined" style="margin-right: 5px; display: flex; align-items:center">security</i><b>WEB CERTIFICATE</b>
                </a>
                <ul class="right">
                    @if (signInManager.IsSignedIn(User))
                    {
                        <li>
                            <a class="dropdown-trigger" href="#!" data-target="dropdown1">
                                <span><i class="material-icons left">account_circle</i>  @User.Identity.Name.ToUpper()</span>
                                <i class="material-icons right">arrow_drop_down</i>
                            </a>
                        </li>
                    }
                    else
                    {
                        <li><a class="waves-effect waves-light btn blue darken-4 z-depth-0" style="margin-right: 0" asp-controller="User" asp-action="Signup">SignUp</a></li>
                        <li><a class="waves-effect waves-light btn blue darken-4 z-depth-0" style="margin-right: 0" asp-controller="User" asp-action="Login">Login</a></li>
                    }
                </ul>
            </div>
        </nav>
        <ul id="dropdown1" class="dropdown-content">
            <li><a asp-controller="Files" asp-action="Index" class="blue-text">Your PDFs</a></li>
            <li><a asp-controller="Certificate" asp-action="Add" class="blue-text">Your Certificate</a></li>
            <li class="divider"></li>
            <li><a asp-controller="User" asp-action="Logout" class="blue-text">Logout</a></li>
        </ul>
    </header>
    <div style="flex: auto">
        <main role="main">
            @RenderBody()
        </main>
    </div>

    <footer class="blue" style="padding: 20px; margin-top: 20px">
        <div class="container white-text" >
            &copy; 2022 - PDF Certificate
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <script>
        $(document).ready(function(){
            $(".dropdown-trigger").dropdown({ coverTrigger: false});
        });
    </script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>